


version: '3.8'

services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - masterclass-data:/root/db
    stdin_open: true
    tty: true

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && ((rake db:migrate) || rake db:setup) && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/masterclass-backend
      - bundle:/usr/local/bundle
      - ./node_modules:/masterclass-backend/node_modules
    tmpfs: /masterclass-backend/tmp
    depends_on:
      - db
    env_file: .env
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"

volumes:
  bundle:
  masterclass-data:
