user_auth = UserAuth.create!(email: 'muhammad.ahmed99@eng-st.cu.edu.eg', password: 'password', password_confirmation: 'password', user_name: 'Alaa', role: 'admin')
Admin.create!(first_name: 'Muhammad', last_name: 'Alaa', birthday: Time.now - 22.years, user_auth_id: user_auth.id)

instructor = UserAuth.create!(email: 'muhammad.hesham99@eng-st.cu.edu.eg', password: 'password', password_confirmation: 'password', user_name: 'Etsh', role: 'instructor')  
Instructor.create!(first_name: 'Muhammad', last_name: 'Ahmed Hisham', birthday: Time.now - 22.years, user_auth_id: instructor.id)

user_auth = UserAuth.create!(email: 'muhmoud.amr99@eng-st.cu.edu.eg', password: 'password', password_confirmation: 'password', user_name: 'Goudy', role: 'learner')
Learner.create!(first_name: 'Muhamoud', last_name: 'Amr', birthday: Time.now - 22.years, user_auth_id: user_auth.id)

user_auth = UserAuth.create!(email: 'houssam.alaa99@eng-st.cu.edu.eg', password: 'password', password_confirmation: 'password', user_name: 'Houso', role: 'learner')
Learner.create!(first_name: 'Housam', last_name: 'Alaa', birthday: Time.now - 22.years, user_auth_id: user_auth.id)
 
course = Course.create!(name: 'Consultation', user_auth: instructor, about: 'this course to understand the basic concepts of conultation and security')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of conultation and security')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of conultation and security')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of conultation and security')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of conultation and security')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of conultation and security')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of conultation and security')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of conultation and security')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of conultation and security')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of conultation and security')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of conultation and security')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 2', description: 'this activity to understand another concepts of conultation and security')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 2', description: 'this activity to understand another concepts of conultation and security')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of conultation and security')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of conultation and security')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of conultation and security')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of conultation and security')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of conultation and security')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of conultation and security')
thread = Comment.create!(user_auth: user_auth, course: course, parent_id: nil, body: "This Course is interesting")
Comment.create!(user_auth: user_auth, course: course, parent_id: thread.id, body: "I really enjoy it!")

course = Course.create!(name: 'Math', user_auth: instructor, about: 'this course to understand the basic concepts of math and calculas 1')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of math and calculas 1')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of math and calculas 1')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of math and calculas 1')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of math and calculas 1')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of math and calculas 1')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of math and calculas 1')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of math and calculas 1')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of math and calculas 1')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of math and calculas 1')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of math and calculas 1')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 2', description: 'this activity to understand another concepts of math and calculas 1')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 2', description: 'this activity to understand another concepts of math and calculas 1')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of math and calculas 1')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of math and calculas 1')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of math and calculas 1')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of math and calculas 1')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of math and calculas 1')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of math and calculas 1')
thread = Comment.create!(user_auth: user_auth, course: course, parent_id: nil, body: "This Course is interesting")
Comment.create!(user_auth: user_auth, course: course, parent_id: thread.id, body: "I really enjoy it!")

course = Course.create!(name: 'Math2', user_auth: instructor, about: 'this course to understand the basic concepts of math and calculas 2')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of math and calculas 2')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of math and calculas 2')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of math and calculas 2')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of math and calculas 2')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of math and calculas 2')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of math and calculas 2')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of math and calculas 2')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of math and calculas 2')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of math and calculas 2')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of math and calculas 2')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 2', description: 'this activity to understand another concepts of math and calculas 2')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 2', description: 'this activity to understand another concepts of math and calculas 2')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of math and calculas 2')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of math and calculas 2')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of math and calculas 2')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of math and calculas 2')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of math and calculas 2')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of math and calculas 2')
thread = Comment.create!(user_auth: user_auth, course: course, parent_id: nil, body: "This Course is interesting")
Comment.create!(user_auth: user_auth, course: course, parent_id: thread.id, body: "I really enjoy it!")

course = Course.create!(name: 'Networks', user_auth: instructor, about: 'this course to understand the basic concepts of networks')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of networks')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of networks')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of networks')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of networks')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of networks')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of networks')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of networks')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of networks')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of networks')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of networks')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 2', description: 'this activity to understand another concepts of networks')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 2', description: 'this activity to understand another concepts of networks')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of networks')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of networks')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of networks')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of networks')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of networks')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of networks')
thread = Comment.create!(user_auth: user_auth, course: course, parent_id: nil, body: "This Course is interesting")
Comment.create!(user_auth: user_auth, course: course, parent_id: thread.id, body: "I really enjoy it!")

course = Course.create!(name: 'Embedded', user_auth: instructor, about: 'this course to understand the basic concepts of embedded systems')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of embedded systems')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of embedded systems')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of embedded systems')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of embedded systems')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of embedded systems')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of embedded systems')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of embedded systems')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of embedded systems')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of embedded systems')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of embedded systems')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 2', description: 'this activity to understand another concepts of embedded systems')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 2', description: 'this activity to understand another concepts of embedded systems')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of embedded systems')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of embedded systems')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of embedded systems')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of embedded systems')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of embedded systems')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of embedded systems')
thread = Comment.create!(user_auth: user_auth, course: course, parent_id: nil, body: "This Course is interesting")
Comment.create!(user_auth: user_auth, course: course, parent_id: thread.id, body: "I really enjoy it!")

course = Course.create!(name: 'Pattarns', user_auth: instructor, about: 'this course to understand the basic concepts of pattarn')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of pattarn')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of pattarn')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of pattarn')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of pattarn')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of pattarn')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of pattarn')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of pattarn')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of pattarn')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of pattarn')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of pattarn')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 2', description: 'this activity to understand another concepts of pattarn')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 2', description: 'this activity to understand another concepts of pattarn')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of pattarn')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of pattarn')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of pattarn')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of pattarn')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of pattarn')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of pattarn')
thread = Comment.create!(user_auth: user_auth, course: course, parent_id: nil, body: "This Course is interesting")
Comment.create!(user_auth: user_auth, course: course, parent_id: thread.id, body: "I really enjoy it!")

course = Course.create!(name: 'ADB', user_auth: instructor, about: 'this course to understand the basic concepts of advanced database')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of advanced database')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of advanced database')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of advanced database')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of advanced database')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of advanced database')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of advanced database')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of advanced database')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of advanced database')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of advanced database')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of advanced database')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 2', description: 'this activity to understand another concepts of advanced database')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 2', description: 'this activity to understand another concepts of advanced database')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of advanced database')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of advanced database')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of advanced database')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of advanced database')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of advanced database')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of advanced database')
thread = Comment.create!(user_auth: user_auth, course: course, parent_id: nil, body: "This Course is interesting")
Comment.create!(user_auth: user_auth, course: course, parent_id: thread.id, body: "I really enjoy it!")

course = Course.create!(name: 'Modeling', user_auth: instructor, about: 'this course to understand the basic concepts of modeling')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of modeling')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of modeling')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of modeling')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of modeling')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of modeling')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 1', description: 'this activity to understand the basic concepts of modeling')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of modeling')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of modeling')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of modeling')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 2', description: 'this activity to understand another concepts of modeling')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 2', description: 'this activity to understand another concepts of modeling')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 2', description: 'this activity to understand another concepts of modeling')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of modeling')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of modeling')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of modeling')
Activity.create!(document: Rails.root.join('public/pdfs/fallback/7_Concurrency_Control.pdf').open, course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of modeling')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of modeling')
Activity.create!(link: "https://www.youtube.com/embed/3PcIJKd1PKU", course: course, name: 'lecture 3', description: 'this activity to understand some very new concepts of modeling')
thread = Comment.create!(user_auth: user_auth, course: course, parent_id: nil, body: "This Course is interesting")
Comment.create!(user_auth: user_auth, course: course, parent_id: thread.id, body: "I really enjoy it!")
